server:
  port: 8080

spring:
  application:
    name: chess-server
  datasource:
    url: jdbc:postgresql://localhost:5432/chess
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
