server:
  port: 8080

spring:
  application:
    name: chess-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chess}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
